logdir: 'results/MNIST/DIM_2/'
logger: 
  type: base
  endwith: ['@']
model:
  arch: eae 
  encoder: 
    arch: conv2fc 
    nh: 8
    nh_mlp: 1024
    out_activation: linear 
  decoder:
    arch: deconv2
    nh: 8
    out_activation: sigmoid 
  x_dim: 784
  z_dim: 16
  energy_ae:
    z_dim: 16
    max_latent_variance: 0.1
data:
  training:
    dataset: MNIST
    root: dataset
    batch_size: 256
    n_workers: 4
    split: training
    shuffle: True
    digits: [0, 2, 3, 4, 5, 6, 7, 8, 9]
  validation:
    dataset: MNIST
    root: dataset
    batch_size: 256
    n_workers: 4
    split: validation
    shuffle: False
    digits: [0, 2, 3, 4, 5, 6, 7, 8, 9]
  test:
    dataset: MNIST
    root: dataset
    batch_size: 256
    n_workers: 4
    split: test
    shuffle: False
    digits: [0, 2, 3, 4, 5, 6, 7, 8, 9]
  OOD_validation:
    dataset: MNIST
    root: dataset
    batch_size: 256
    n_workers: 4
    split: validation
    shuffle: False
    digits: [1]
  OOD_test:
    dataset: MNIST
    root: dataset
    batch_size: 256
    n_workers: 4
    split: test
    shuffle: False
    digits: [1]
  
trainer: base
training:
  n_epoch: 1500
  n_epoch_pre: 100
  n_epoch_ebm: 30
  fix_decoder: false
  optimizer_pre:
    name: 'adam'
    lr: 1e-4
  optimizer:
    lr_encoder: 1e-4
    lr_decoder: 1e-4
    lr_constant: 1e-3
    lr_sigma: 1e-4
  print_interval: 200
  val_interval: 200
  visualize_interval: 200

 